version: "3"

services:
  app:
    build: ..
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - uploads-data:/app/public/uploads

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: recipeforum
      POSTGRES_PASSWORD: recipeforum
      POSTGRES_DB: recipeforum
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
  uploads-data:
